### ISSUE TITLE
Not able to test on an image

### ISSUE THREAD

**Issue by Vinayak-VG** [Algolzw/daclip-uir#27]
I get this error when I run the code given in the readme file for testing on an image

Traceback (most recent call last):
  File "run.py", line 6, in <module>
    model, preprocess = open_clip.create_model_from_pretrained('daclip_ViT-B-32', pretrained=checkpoint)
  File "/home/vinayak/.local/lib/python3.8/site-packages/open_clip/factory.py", line 437, in create_model_from_pretrained
    model = create_model(
  File "/home/vinayak/.local/lib/python3.8/site-packages/open_clip/factory.py", line 215, in create_model
    raise RuntimeError(f'Model config for {model_name} not found.')
RuntimeError: Model config for daclip_ViT-B-32 not found.

Please let us know what has to be done?

**Comment by Algolzw** [comment]
Hi, which code are you running? I've tried the [app.py](https://github.com/Algolzw/daclip-uir/blob/d16309bb17f2c9c702e558ac756397e661aa1a52/universal-image-restoration/config/daclip-sde/app.py) and it runs very well.

**Comment by Algolzw** [comment]
Moreover, our project hasn't been merged into the official open_clip repo. Thus you probably should use our [open_clip](https://github.com/Algolzw/daclip-uir/tree/d16309bb17f2c9c702e558ac756397e661aa1a52/universal-image-restoration/open_clip) that contains the modified code for our DA-CLIP.

**Comment by lwtgithublwt** [comment]
> RuntimeError: Model config for daclip_ViT-B-32 not found.
I'm not sure if you have solved this problem. Can you answer it
