### ISSUE TITLE
csv

### ISSUE THREAD

**Issue by wjkbigface** [Algolzw/daclip-uir#42]
(daclip) root@autodl-container-fe1f429743-4d498b12:~# python /root/autodl-fs/daclip-uir-main/scripts/generate_captions.py
Loading caption model blip-large...
Loading CLIP model ViT-L-14/openai...
Traceback (most recent call last):
  File "/root/autodl-fs/daclip-uir-main/scripts/generate_captions.py", line 72, in <module>
    ci = Interrogator(Config(clip_model_name="ViT-L-14/openai",
  File "/root/miniconda3/envs/daclip/lib/python3.10/site-packages/clip_interrogator/clip_interrogator.py", line 72, in __init__
    self.load_clip_model()
  File "/root/miniconda3/envs/daclip/lib/python3.10/site-packages/clip_interrogator/clip_interrogator.py", line 106, in load_clip_model
    self.clip_model, _, self.clip_preprocess = open_clip.create_model_and_transforms(
  File "/root/miniconda3/envs/daclip/lib/python3.10/site-packages/open_clip/factory.py", line 384, in create_model_and_transforms
    model = create_model(
  File "/root/miniconda3/envs/daclip/lib/python3.10/site-packages/open_clip/factory.py", line 290, in create_model
    load_checkpoint(model, checkpoint_path)
  File "/root/miniconda3/envs/daclip/lib/python3.10/site-packages/open_clip/factory.py", line 161, in load_checkpoint
    incompatible_keys = model.load_state_dict(state_dict, strict=strict)
  File "/root/miniconda3/envs/daclip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIP:生成csv文件时出错

**Comment by wjkbigface** [comment]
> Hi, I haven't seen this problem before, and have you solved it now?

Hello, it has been solved in Windows environment, thank you very much
