### ISSUE TITLE
预训练文件

### ISSUE THREAD

**Issue by Lincoln20030413** [Algolzw/daclip-uir#65]
Traceback (most recent call last):
  File "/opt/data/private/daclip-uir-main/universal-image-restoration/config/daclip-sde/train.py", line 356, in <module>
    main()
  File "/opt/data/private/daclip-uir-main/universal-image-restoration/config/daclip-sde/train.py", line 205, in main
    clip_model, preprocess = open_clip.create_model_from_pretrained('daclip_ViT-B-32', pretrained=opt['path']['daclip'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/data/private/daclip-uir-main/universal-image-restoration/config/daclip-sde/../../open_clip/factory.py", line 379, in create_model_from_pretrained
    model = create_model(
            ^^^^^^^^^^^^^
  File "/opt/data/private/daclip-uir-main/universal-image-restoration/config/daclip-sde/../../open_clip/factory.py", line 247, in create_model
    raise RuntimeError(error_str)
RuntimeError: Pretrained weights (pretrained/daclip_ViT-B-32.pt) not found for model daclip_ViT-B-32.Available pretrained tags ([].

**Comment by Lincoln20030413** [comment]
感谢您的工作！请问该路径文件opt['path']['daclip']训练时必须得提供吗？如果必须要提供的话，请问要通过哪个链接下载
